import { headers } from "next/headers";
import { redirect } from "next/navigation";
import LeadForm from "./lead-form";

const redirectHosts = new Set(["www.leontieva.media", "leontievamedia.ru", "www.leontievamedia.ru"]);

const entryProducts = [
  { number: "01", label: "Разовый продукт", title: "Стратегическое решение для собственника", text: "Позиция, приоритеты и маршрут, который можно передать команде и запустить в работу.", result: "Результат: согласованный комплект решения", duration: "Срок: фиксируется после вводных", href: "/strategy/?source=home-start" },
  { number: "02", label: "Под конкретную дату", title: "Подготовка к интервью или выступлению", text: "Факты, ключевые сообщения, сложные вопросы и репетиционный контур перед важным выходом.", result: "Результат: готовый комплект подготовки", duration: "Срок: привязан к событию", href: "/interview/?source=home-start" },
  { number: "03", label: "От 3 месяцев", title: "Регулярное сопровождение первого лица", text: "Единый маршрут, календарь, материалы, производство, приёмка и оценка следующего цикла.", result: "Результат: рабочая система публичной деятельности", duration: "Объём уточняется каждые 90 дней", href: "/support/?source=home-start" },
];

const cases = [
  { type: "Производственная компания · Система", title: "От отдельных выходов — к управляемой публичной траектории", rows: [["Задача", "Связать публичную роль первого лица с реальными фактами бизнеса."], ["Работа", "Стратегическая сессия, позиционирование, доказательная база, темы и календарь."], ["Принятый продукт", "Согласованный 90-дневный маршрут с владельцами, сроками и контрольными точками."], ["Использование", "Маршрут стал основанием для постановки задач команде и следующего производственного цикла."]] },
  { type: "Репутационный риск · Решение", title: "Интервью остановлено до публикации", rows: [["Задача", "Понять, усиливает ли большой материал позицию героя или создаёт новые риски."], ["Работа", "Фактчекинг, редакционный разбор, оценка контекста и возможного использования."], ["Принятый продукт", "Решение не выпускать длинную версию и комплект безопасных фрагментов."], ["Использование", "Материалы сохранены для точечного применения; создан стандарт будущих интервью."]] },
  { type: "Первое лицо · Подготовка", title: "Публичный выход собран до начала съёмки", rows: [["Задача", "Подготовить первого человека к интервью и сохранить управляемую подачу."], ["Работа", "Проверка фактов, карта тезисов, сложные вопросы и сценарий использования."], ["Принятый продукт", "Согласованный комплект подготовки для первого лица и съёмочной команды."], ["Использование", "Материал введён в производство; следующий цикл зафиксирован по результатам выхода."]] },
];

const fitSignals = [
  "Есть реальный бизнес, экспертиза или общественная роль, подтверждённые фактами.",
  "В работе участвует собственник, первое лицо или человек с правом принимать решения.",
  "Понятно, что должно измениться и к какому сроку нужен результат.",
  "Команда готова предоставлять документы, вводные и доступ к ответственным людям.",
  "Есть бюджет на законченный продукт или сопровождение от трёх месяцев.",
  "Принимается, что решения редакций, органов власти и других третьих лиц нельзя гарантировать.",
];

export const dynamic = "force-dynamic";

export default async function Home() {
  const host = ((await headers()).get("host") ?? "").split(":")[0].toLowerCase();
  if (redirectHosts.has(host)) redirect("https://leontieva.media");

  return (
    <main>
      <header className="site-header">
        <a className="brand" href="#top" aria-label="LEONTIEVA — продюсерский центр, на главную"><img src="/lm-icon.jpg" alt="" /><span><strong>LEONTIEVA</strong><small>ПРОДЮСЕРСКИЙ ЦЕНТР</small></span></a>
        <nav aria-label="Навигация"><a href="#start">Начать</a><a href="#approach">Как работаем</a><a href="#cases">Практика</a><a href="#team">Елена</a></nav>
        <a className="header-cta" href="#contact">Обсудить задачу</a>
      </header>

      <section className="hero hero-v3" id="top">
        <div className="hero-copy"><p className="eyebrow">Стратегия · Первое лицо · Медиа · Продюсирование</p><h1>Публичная траектория, <em>которая работает на задачу</em></h1><p className="hero-lead">LEONTIEVA соединяет стратегию, подготовку первого лица и производство в один управляемый маршрут — от решения до принятого результата.</p><div className="hero-actions"><a className="button button-gold" href="#start">Выбрать первый формат</a><a className="text-link text-link-light" href="#approach">Как устроена работа <span>↘</span></a></div><p className="hero-note">Сначала определяем, что именно должно измениться. Затем фиксируем продукт, границы, срок и критерии приёмки.</p></div>
        <figure className="hero-media hero-portrait"><img src="/elena-hero-v4.jpg" alt="Елена Леонтьева — основатель и главный продюсер LEONTIEVA" /><figcaption className="hero-person"><span>Елена Леонтьева</span><small>Основатель и главный продюсер</small></figcaption></figure>
      </section>

      <section className="trust-strip" aria-label="Принципы работы"><div><strong>01</strong><span>Личное ведение</span></div><div><strong>02</strong><span>Проверка фактов</span></div><div><strong>03</strong><span>Стратегия и исполнение</span></div><div><strong>04</strong><span>Конфиденциальность</span></div></section>

      <section className="editorial-section"><div className="editorial-stage"><img className="editorial-photo editorial-photo-production" src="/elena-production-v4.jpg" alt="Елена Леонтьева во время подготовки и записи медиаматериала" /><div className="editorial-card"><p className="section-kicker">Когда мы особенно полезны</p><h2>Когда публичность должна привести к решению</h2><p className="lead-paragraph">Не добавляем активности ради присутствия. Собираем факты, интересы и риски в понятную траекторию действий.</p><ol className="editorial-list"><li><b>Новый уровень</b><span>Нужно заново определить роль, позицию и публичный маршрут лидера или компании.</span></li><li><b>Высокие ставки</b><span>Предстоит интервью, запуск, переговоры или сложная общественная ситуация.</span></li><li><b>Несколько контуров</b><span>Бизнес, медиа и стейкхолдеры должны двигаться в одной логике, а не параллельно.</span></li></ol></div></div></section>

      <section className="start-section" id="start"><div className="section-heading"><div><p className="section-kicker">Начать отсюда</p><h2>Три понятных<br />входа в работу</h2></div><p>Не нужно заранее выбирать все услуги. Достаточно назвать ближайшую задачу — для неё определяется законченный продукт, срок, границы и стоимость.</p></div><div className="entry-product-grid">{entryProducts.map((product, index) => <article className={`entry-product-card ${index === 0 ? "entry-product-featured" : ""}`} key={product.number}><div><span className="entry-product-number">{product.number}</span><span className="card-label">{product.label}</span></div><h3>{product.title}</h3><p>{product.text}</p><ul><li>{product.result}</li><li>{product.duration}</li><li>Стоимость: после 20-минутной квалификации</li></ul><a href={product.href}>Посмотреть формат <span>→</span></a></article>)}</div><p className="start-note"><b>Первый разговор — до 20 минут.</b> Это взаимная квалификация задачи, а не бесплатная стратегическая консультация.</p></section>

      <section className="explain-section" id="explain"><div className="explain-intro"><p className="section-kicker">Если объяснить простыми словами</p><h2>Мы не выдаём список советов. Мы ведём по маршруту.</h2><p className="lead-paragraph">Это похоже на работу хорошего персонального тренера: сначала нужно понять исходную точку, цель и ограничения. Только после этого можно построить реалистичный план, проверить его в действии и корректировать по фактам.</p><p className="explain-quote">Публичная траектория создаётся вместе с клиентом — её нельзя купить как готовый абонемент и выполнить без участия первого лица.</p></div><div className="explain-flow"><article><span>01</span><div><h3>Вы определяете цель и принимаете решения</h3><p>Предоставляете факты, вводные, доступ к ответственным людям и вовремя подтверждаете ключевые действия.</p></div></article><article><span>02</span><div><h3>Мы строим систему и ведём исполнение</h3><p>Диагностируем ситуацию, собираем маршрут, готовим продукты, координируем участников и проверяем качество.</p></div></article><article><span>03</span><div><h3>Третьи лица принимают собственные решения</h3><p>Редакции, органы власти, банки, партнёры и аудитория не находятся под нашим управлением — поэтому мы не обещаем их решения.</p></div></article><aside className="contour-note"><p>Одна цель — один контур работы</p><h3>Продюсирование, общественный или GR-проект и привлечение финансирования могут быть связаны общей стратегией, но не являются одной услугой.</h3><p>Для каждого контура определяются свой результат, команда, сроки, объём и стоимость. Если задача расширяется, новый контур согласовывается отдельно.</p></aside></div></section>

      <section className="approach-section" id="approach"><div className="approach-copy"><p className="section-kicker">Как мы работаем</p><h2>Не занятость команды, а принятый продукт</h2><p>До начала работы называем конкретный результат, границы, срок, цену и критерии приёмки. Всё существенное фиксируется письменно.</p><ol className="mini-process seven-steps"><li><b>01 · Вход</b><span>владелец, задача, срок</span></li><li><b>02 · Результат</b><span>продукт, пользователь, критерии</span></li><li><b>03 · Предложение</b><span>объём, цена, границы, риски</span></li><li><b>04 · Старт</b><span>договор, оплата, вводные, доступы</span></li><li><b>05 · Производство</b><span>работа, фактчекинг, версии</span></li><li><b>06 · Запуск</b><span>передача и письменная приёмка</span></li><li><b>07 · Оценка</b><span>использование, реакция, следующий цикл</span></li></ol></div><figure className="process-figure process-figure-premium"><img src="/process-flow-client-v2.png" alt="Схема работы: что клиент даёт, что делает продюсерский центр и какой результат получает" /><figcaption>Вы передаёте цель, факты и решения ответственного. Мы превращаем их в готовый продукт, понятный способ использования и следующий шаг.</figcaption></figure></section>

      <section className="measurement-section"><div><p className="section-kicker">Как понимаем результат</p><h2>Измеряем не только выход,<br />но и его использование.</h2></div><div className="measurement-grid"><article><span>0</span><b>Приёмка</b><p>Комплект передан и соответствует согласованным критериям.</p></article><article><span>7</span><b>Использование</b><p>Понятно, кем и как результат введён в работу.</p></article><article><span>30</span><b>Ближайший результат</b><p>Проверяем реакцию, качество и необходимую корректировку.</p></article><article><span>90</span><b>Следующий цикл</b><p>Решаем: продолжить, изменить, усилить или остановить.</p></article></div></section>

      <section className="cases-section" id="cases"><div className="section-heading"><div><p className="section-kicker">Практика</p><h2>Задача → работа →<br />принятый продукт</h2></div><p>Кейсы обезличены: показываем профессиональную логику и использование результата, не раскрывая клиентов и чувствительные сведения.</p></div><div className="case-grid case-grid-three">{cases.map((item, index) => <article className={`case-card ${index === 1 ? "case-card-accent" : ""}`} key={item.title}><p className="case-type">{item.type}</p><h3>{item.title}</h3><dl>{item.rows.map(([term, description]) => <div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl></article>)}</div></section>

      <section className="fit-section-v4"><div className="fit-heading"><p className="section-kicker">Взаимная квалификация</p><h2>Мы подходим друг другу, если…</h2><p>Эти условия помогают не тратить время на предложения, которые невозможно качественно выполнить.</p></div><div className="fit-signal-grid">{fitSignals.map((signal, index) => <article key={signal}><span>{String(index + 1).padStart(2, "0")}</span><p>{signal}</p></article>)}</div><aside><b>Не наш формат:</b> запрос на гарантированный эфир, решение органа власти, «сделайте всё без участия первого лица» или бесплатную разработку стратегии до договора.</aside></section>

      <section className="gr-section gr-v3" id="gr"><div className="gr-heading"><p className="section-kicker">Дополнительный контур</p><h2>GR и общественные проекты</h2><p className="boundary-note"><b>Граница:</b> мы не гарантируем решения органов власти и третьих лиц, не продаём доступ, должности или административный результат.</p></div><div className="gr-panel"><p className="lead-paragraph">Подключаем этот контур, когда он действительно нужен основной стратегии: проверяем факты и полномочия, готовим позицию, материалы и следующий законный шаг.</p><ol><li><span>01</span><b>Проверяем факты, интересы и риски</b></li><li><span>02</span><b>Собираем карту участников и решений</b></li><li><span>03</span><b>Готовим позицию, материалы и встречи</b></li><li><span>04</span><b>Фиксируем договорённости и контроль</b></li></ol></div></section>

      <section className="team-section team-v3" id="team"><figure className="team-portrait"><img src="/elena-about-v3.jpg" alt="Елена Леонтьева" /><figcaption>Елена Леонтьева · Основатель и главный продюсер</figcaption></figure><div className="team-copy"><p className="section-kicker">Senior-led</p><h2>Ключевые решения — лично у Елены</h2><p className="lead-paragraph">Елена отвечает за публичную логику, позиционирование, подготовку первого лица и качество результата на всём маршруте.</p><p>Проектная команда собирается под задачу: редакторы, медиапродюсеры, телевизионные и съёмочные команды, дизайнеры, аналитики, юристы и отраслевые эксперты. Клиент получает не перечень специалистов, а единый контур ответственности.</p><div className="team-principles"><div><b>Личное ведение</b><span>Ключевые решения не передаются младшей команде.</span></div><div><b>Команда под продукт</b><span>Подключаются только нужные компетенции и исполнители.</span></div><div><b>Один стандарт качества</b><span>Факты, версии, права и итоговая приёмка контролируются в одном процессе.</span></div></div></div></section>

      <section className="contact-section" id="contact"><div className="contact-copy"><p className="section-kicker">Конфиденциальный первый шаг</p><h2>Сначала определим, что должно измениться</h2><p>Коротко опишите ситуацию. На 20-минутном разговоре проверим взаимное совпадение и определим подходящий формат работы.</p><div className="contact-prompts"><span>Есть ли конкретная задача и срок?</span><span>Кто принимает решение?</span><span>Какие факты и материалы уже есть?</span></div><a className="contact-email contact-email-light" href="mailto:pr@leontieva-media.ru" data-conversion="email">pr@leontieva-media.ru</a></div><LeadForm source="home-contact" /></section>

      <footer><a className="brand footer-brand" href="#top"><img src="/lm-icon.jpg" alt="" /><span><strong>LEONTIEVA</strong><small>ПРОДЮСЕРСКИЙ ЦЕНТР</small></span></a><div className="footer-links"><a href="/strategy/">Стратегия</a><a href="/interview/">Интервью</a><a href="/support/">Сопровождение</a></div><p>© 2026 LEONTIEVA</p></footer>
    </main>
  );
}
