import { headers } from "next/headers";
import { redirect } from "next/navigation";

const redirectHosts = new Set(["www.leontieva.media", "leontievamedia.ru", "www.leontievamedia.ru"]);

const services = [
  { number: "01", label: "Основа", title: "Стратегия и публичная траектория", text: "Определяем цель, роль, доказательную базу, ограничения и последовательность решений.", points: ["диагностика и стратегическая сессия", "позиционирование и ключевые сообщения", "дорожная карта и критерии результата"], link: "Обсудить стратегию →" },
  { number: "02", title: "Медиа и продюсирование", text: "Готовим первого человека и материалы, координируем производство, версии и использование результата.", points: ["PR-сопровождение и медиаплан", "интервью, ТВ, подкасты и видео", "подготовка к сложным вопросам"], link: "Обсудить сопровождение →" },
  { number: "03", title: "GR и общественные проекты", text: "Выстраиваем законный диалог с деловыми, отраслевыми, общественными и государственными структурами.", points: ["карта стейкхолдеров и рисков", "позиция и подготовка встреч", "протокол решений и следующий шаг"], link: "Посмотреть границы работы →" },
];

const cases = [
  { type: "Производственная компания · Система", title: "От отдельных выходов — к управляемой публичной траектории", rows: [["Задача", "Связать публичную роль первого лица с реальными фактами бизнеса."], ["Работа", "Стратегическая сессия, позиционирование, доказательная база, темы и календарь."], ["Результат", "Согласованный 90-дневный маршрут с владельцами, сроками и контрольными точками."]] },
  { type: "Репутационный риск · Решение", title: "Интервью остановлено до публикации", rows: [["Задача", "Понять, усиливает ли большой материал позицию героя или создаёт новые риски."], ["Работа", "Фактчекинг, редакционный разбор, оценка контекста и возможного использования."], ["Результат", "Длинная версия не выпущена; безопасные фрагменты сохранены, создан стандарт будущих интервью."]] },
];

export const dynamic = "force-dynamic";

export default async function Home() {
  const host = ((await headers()).get("host") ?? "").split(":")[0].toLowerCase();
  if (redirectHosts.has(host)) redirect("https://leontieva.media");

  return (
    <main>
      <header className="site-header">
        <a className="brand" href="#top" aria-label="LEONTIEVA — продюсерский центр, на главную"><img src="/lm-icon.jpg" alt="" /><span><strong>LEONTIEVA</strong><small>ПРОДЮСЕРСКИЙ ЦЕНТР</small></span></a>
        <nav aria-label="Навигация"><a href="#services">Направления</a><a href="#approach">Как работаем</a><a href="#cases">Практика</a><a href="#team">Елена</a></nav>
        <a className="header-cta" href="#contact">Обсудить задачу</a>
      </header>

      <section className="hero hero-v3" id="top">
        <div className="hero-copy"><p className="eyebrow">Стратегия · Медиа · Продюсирование · GR</p><h1>Публичная траектория, <em>которая работает на задачу</em></h1><p className="hero-lead">LEONTIEVA соединяет стратегию, подготовку первого лица, медиа и работу со стейкхолдерами в один управляемый маршрут — от решения до принятого результата.</p><div className="hero-actions"><a className="button button-gold" href="#contact">Обсудить задачу</a><a className="text-link text-link-light" href="#approach">Как устроена работа <span>↘</span></a></div><p className="hero-note">Сначала определяем, что именно должно измениться. Затем фиксируем продукт, границы, срок и критерии приёмки.</p></div>
        <figure className="hero-media hero-portrait"><img src="/elena-hero-v4.jpg" alt="Елена Леонтьева — основатель и главный продюсер LEONTIEVA" /><figcaption className="hero-person"><span>Елена Леонтьева</span><small>Основатель и главный продюсер</small></figcaption></figure>
      </section>

      <section className="trust-strip" aria-label="Принципы работы"><div><strong>01</strong><span>Личное ведение</span></div><div><strong>02</strong><span>Проверка фактов</span></div><div><strong>03</strong><span>Стратегия и исполнение</span></div><div><strong>04</strong><span>Конфиденциальность</span></div></section>

      <section className="editorial-section"><div className="editorial-stage"><img className="editorial-photo editorial-photo-production" src="/elena-production-v4.jpg" alt="Елена Леонтьева во время подготовки и записи медиаматериала" /><div className="editorial-card"><p className="section-kicker">Когда мы особенно полезны</p><h2>Когда публичность должна привести к решению</h2><p className="lead-paragraph">Не добавляем активности ради присутствия. Собираем факты, интересы и риски в понятную траекторию действий.</p><ol className="editorial-list"><li><b>Новый уровень</b><span>Нужно заново определить роль, позицию и публичный маршрут лидера или компании.</span></li><li><b>Высокие ставки</b><span>Предстоит интервью, запуск, переговоры или сложная общественная ситуация.</span></li><li><b>Несколько контуров</b><span>Бизнес, медиа и стейкхолдеры должны двигаться в одной логике, а не параллельно.</span></li></ol></div></div></section>

      <section className="services-section services-v3" id="services"><div className="section-heading"><div><p className="section-kicker">Три контура работы</p><h2>Одна задача.<br />Один маршрут.</h2></div><p>Формат собирается под ситуацию: от стратегической сессии и отдельного продукта до регулярного сопровождения.</p></div><div className="service-grid">{services.map((service, index) => <article className={`service-card ${index === 0 ? "service-card-featured" : ""} ${index === 2 ? "service-card-gr" : ""}`} key={service.number}>{service.label && <span className="card-label">{service.label}</span>}<p className="service-number">{service.number}</p><h3>{service.title}</h3><p>{service.text}</p><ul>{service.points.map((point) => <li key={point}>{point}</li>)}</ul><a href={index === 2 ? "#gr" : "#contact"}>{service.link}</a></article>)}</div></section>

      <section className="explain-section" id="explain"><div className="explain-intro"><p className="section-kicker">Если объяснить простыми словами</p><h2>Мы не выдаём список советов. Мы ведём по маршруту.</h2><p className="lead-paragraph">Это похоже на работу хорошего персонального тренера: сначала нужно понять исходную точку, цель и ограничения. Только после этого можно построить реалистичный план, проверить его в действии и корректировать по фактам.</p><p className="explain-quote">Публичная траектория создаётся вместе с клиентом — её нельзя купить как готовый абонемент и выполнить без участия первого лица.</p></div><div className="explain-flow"><article><span>01</span><div><h3>Вы определяете цель и принимаете решения</h3><p>Предоставляете факты, вводные, доступ к ответственным людям и вовремя подтверждаете ключевые действия.</p></div></article><article><span>02</span><div><h3>Мы строим систему и ведём исполнение</h3><p>Диагностируем ситуацию, собираем маршрут, готовим продукты, координируем участников и проверяем качество.</p></div></article><article><span>03</span><div><h3>Третьи лица принимают собственные решения</h3><p>Редакции, органы власти, банки, партнёры и аудитория не находятся под нашим управлением — поэтому мы не обещаем их решения.</p></div></article><aside className="contour-note"><p>Одна цель — один контур работы</p><h3>Продюсирование, общественный или GR-проект и привлечение финансирования могут быть связаны общей стратегией, но не являются одной услугой.</h3><p>Для каждого контура определяются свой результат, команда, сроки, объём и стоимость. Если задача расширяется, новый контур согласовывается отдельно.</p></aside></div></section>

      <section className="approach-section" id="approach"><div className="approach-copy"><p className="section-kicker">Как мы работаем</p><h2>Не занятость команды, а принятый продукт</h2><p>До начала работы называем конкретный результат, границы, срок, цену и критерии приёмки. Всё существенное фиксируется письменно.</p><ol className="mini-process seven-steps"><li><b>01 · Вход</b><span>владелец, задача, срок</span></li><li><b>02 · Результат</b><span>продукт, пользователь, критерии</span></li><li><b>03 · Предложение</b><span>объём, цена, границы, риски</span></li><li><b>04 · Старт</b><span>договор, оплата, вводные, доступы</span></li><li><b>05 · Производство</b><span>работа, фактчекинг, версии</span></li><li><b>06 · Запуск</b><span>передача и письменная приёмка</span></li><li><b>07 · Оценка</b><span>использование, реакция, следующий цикл</span></li></ol></div><figure className="process-figure process-figure-premium"><img src="/process-flow-client-v2.png" alt="Схема работы: что клиент даёт, что делает продюсерский центр и какой результат получает" /><figcaption>Вы передаёте цель, факты и решения ответственного. Мы превращаем их в готовый продукт, понятный способ использования и следующий шаг.</figcaption></figure></section>

      <section className="measurement-section"><div><p className="section-kicker">Как понимаем результат</p><h2>Измеряем не только выход,<br />но и его использование.</h2></div><div className="measurement-grid"><article><span>0</span><b>Приёмка</b><p>Комплект передан и соответствует согласованным критериям.</p></article><article><span>7</span><b>Использование</b><p>Понятно, кем и как результат введён в работу.</p></article><article><span>30</span><b>Ближайший результат</b><p>Проверяем реакцию, качество и необходимую корректировку.</p></article><article><span>90</span><b>Следующий цикл</b><p>Решаем: продолжить, изменить, усилить или остановить.</p></article></div></section>

      <section className="cases-section" id="cases"><div className="section-heading"><div><p className="section-kicker">Практика</p><h2>Результат иногда —<br />не публиковать.</h2></div><p>Кейсы обезличены: показываем профессиональную логику и рабочий результат, не раскрывая клиентов и чувствительные сведения.</p></div><div className="case-grid case-grid-two">{cases.map((item, index) => <article className={`case-card ${index === 1 ? "case-card-accent" : ""}`} key={item.title}><p className="case-type">{item.type}</p><h3>{item.title}</h3><dl>{item.rows.map(([term, description]) => <div key={term}><dt>{term}</dt><dd>{description}</dd></div>)}</dl></article>)}</div></section>

      <section className="gr-section gr-v3" id="gr"><div className="gr-heading"><p className="section-kicker">GR и общественные проекты</p><h2>Законный диалог.<br />Без продажи доступа.</h2><p className="boundary-note"><b>Граница:</b> мы не гарантируем решения органов власти и третьих лиц, не продаём доступ, должности или административный результат.</p></div><div className="gr-panel"><p className="lead-paragraph">Помогаем подготовить позицию и следующий шаг так, чтобы интересы бизнеса, общественная ценность и реальные полномочия участников были разделены и понятны.</p><ol><li><span>01</span><b>Проверяем факты, интересы и риски</b></li><li><span>02</span><b>Собираем карту участников и решений</b></li><li><span>03</span><b>Готовим позицию, материалы и встречи</b></li><li><span>04</span><b>Фиксируем договорённости и контроль</b></li></ol></div></section>

      <section className="team-section team-v3" id="team"><figure className="team-portrait"><img src="/elena-about-v3.jpg" alt="Елена Леонтьева" /><figcaption>Елена Леонтьева · Основатель и главный продюсер</figcaption></figure><div className="team-copy"><p className="section-kicker">Senior-led</p><h2>Ключевые решения — лично у Елены</h2><p className="lead-paragraph">Елена отвечает за публичную логику, позиционирование, подготовку первого лица и качество результата на всём маршруте.</p><p>Проектная команда собирается под задачу: редакторы, медиапродюсеры, телевизионные и съёмочные команды, дизайнеры, аналитики, юристы и отраслевые эксперты. Клиент получает не перечень специалистов, а единый контур ответственности.</p><div className="team-principles"><div><b>Личное ведение</b><span>Ключевые решения не передаются младшей команде.</span></div><div><b>Команда под продукт</b><span>Подключаются только нужные компетенции и исполнители.</span></div><div><b>Один стандарт качества</b><span>Факты, версии, права и итоговая приёмка контролируются в одном процессе.</span></div></div></div></section>

      <section className="contact-section" id="contact"><div className="contact-copy"><p className="section-kicker">Конфиденциальный первый шаг</p><h2>Сначала определим, что должно измениться</h2><p>Коротко опишите ситуацию. На первом разговоре проверим, можем ли быть полезны, и определим подходящий формат работы.</p><div className="contact-prompts"><span>Кто вы и чем занимаетесь?</span><span>Что и для кого должно измениться?</span><span>Что уже сделано и к какому сроку нужен результат?</span></div></div><div className="contact-card"><p className="contact-label">Прямой контакт</p><a className="contact-email" href="mailto:pr@leontieva-media.ru?subject=Обсудить%20задачу">pr@leontieva-media.ru</a><p>Ответим, уточним необходимые вводные и предложим следующий шаг. Стоимость определяется после короткой диагностики задачи и состава продукта.</p><a className="button button-gold contact-button" href="mailto:pr@leontieva-media.ru?subject=Обсудить%20задачу">Начать разговор</a></div></section>

      <footer><a className="brand footer-brand" href="#top"><img src="/lm-icon.jpg" alt="" /><span><strong>LEONTIEVA</strong><small>ПРОДЮСЕРСКИЙ ЦЕНТР</small></span></a><p>Факты · Стратегия · Результат</p><p>© 2026 LEONTIEVA</p></footer>
    </main>
  );
}
